name: Deploy Resume to Azure

on:
  push:
    branches:
      - main

  workflow_dispatch:  # 👈 Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Upload files to Azure Storage
        run: |
          az storage blob upload-batch \
            --destination \$web \
            --account-name rhysresumeweb \
            --source . \
            --overwrite
